export interface Product {
  id: string;
  name: string;
  category: "Utilities" | "Jewellery" | "Dresses";
  price: number;
  rating: number;
  reviewsCount: number;
  image: string;
  images: string[];
  video: string;
  description: string;
  features: string[];
  colors: string[];
  sizes?: string[];
  isNew?: boolean;
  isPopular?: boolean;
}

export const PRODUCTS: Product[] = [
  // UTILITIES (22 products)
  {
    id: "u1",
    name: "Mag-Charge Desk Base",
    category: "Utilities",
    price: 89.99,
    rating: 4.7,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Consolidate your charging with this CNC-machined walnut and aluminum desk base. Powers your phone, watch, and earbuds simultaneously with MagSafe-compatible 15W wireless charging.",
    features: ["Genuine premium walnut top", "15W fast wireless charging", "USB-C Power Delivery", "Heavy non-slip base"],
    colors: ["#78350F", "#4B5563"],
    isPopular: true
  },
  {
    id: "u2",
    name: "Thermostatic Hydro Flask",
    category: "Utilities",
    price: 39.50,
    rating: 4.9,
    reviewsCount: 215,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1604928141064-207cdf6f073f?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Keep your drinks ice-cold for 24 hours or steaming hot for 12 hours. Uses double-wall vacuum insulation with a durable powder-coated exterior and leak-proof lock cap.",
    features: ["TempShield vacuum insulation", "18/8 Pro-grade stainless steel", "BPA-Free design", "Premium powder-coat grip"],
    colors: ["#0284C7", "#DC2626", "#059669"],
    sizes: ["18 oz", "24 oz", "32 oz"]
  },
  {
    id: "u3",
    name: "Ergo-Lift Laptop Stand",
    category: "Utilities",
    price: 65.00,
    rating: 4.8,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=400&q=80"
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Elevate your screen to eye level. Crafted from sandblasted aircraft-grade aluminium with premium silicone padding to prevent scratches and slide.",
    features: ["Aircraft-grade aluminium", "Ergonomic height adjustment", "Heat-dissipating airflow", "Non-slip silicone padding"],
    colors: ["#D1D5DB", "#4B5563"],
    isNew: true
  },
  {
    id: "u4",
    name: "Orbit Key Organiser",
    category: "Utilities",
    price: 42.00,
    rating: 4.6,
    reviewsCount: 78,
    image: "https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=400&q=80"
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Transform your messy key ring into a silent, organized stack. Handcrafted from top-grain Saffiano leather with custom stainless steel hardware.",
    features: ["Saffiano leather", "No-jingle locking mechanism", "Holds 2-7 standard keys", "Integrated D-ring attachment"],
    colors: ["#111827", "#78350F", "#1E3A8A"]
  },
  {
    id: "u5",
    name: "Studio Acoustic Panels",
    category: "Utilities",
    price: 120.00,
    rating: 4.7,
    reviewsCount: 45,
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Professional felt panels designed to absorb echoes and background noise. Made from eco-friendly recycled PET fibers with peel-and-stick adhesive.",
    features: ["Recycled PET felt", "0.85 Noise Reduction Coefficient", "Easy peel-and-stick backing", "Beveled edge design"],
    colors: ["#374151", "#9CA3AF"]
  },
  {
    id: "u6",
    name: "Loom Cord Wrapper",
    category: "Utilities",
    price: 28.00,
    rating: 4.5,
    reviewsCount: 39,
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Keep your charging cables neatly wound. Built from premium full-grain leather with integrated high-grade neodymium magnets for secure wrapping.",
    features: ["Full-grain leather", "Strong neodymium magnets", "Compact travel design", "Set of 3 wraps"],
    colors: ["#78350F", "#000000"]
  },
  {
    id: "u7",
    name: "Desk Felt Blotter",
    category: "Utilities",
    price: 55.00,
    rating: 4.8,
    reviewsCount: 134,
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A comfortable desk writing pad crafted from 100% Merino wool felt. Provides a soft workspace surface while protecting your desk from scratches.",
    features: ["100% Merino wool felt", "Non-slip cork backing", "Provides wrist warmth", "Precision stitching"],
    colors: ["#374151", "#D1D5DB"]
  },
  {
    id: "u8",
    name: "Mag-Stand Travel Duo",
    category: "Utilities",
    price: 79.99,
    rating: 4.9,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Foldable wireless travel charger that powers both your iPhone and Apple Watch. Pocket-sized design makes it the ultimate travel companion.",
    features: ["Foldable travel design", "Dual MagSafe charging", "Includes USB-C cable", "Weighted non-slip base"],
    colors: ["#111827", "#ffffff"],
    isPopular: true
  },
  {
    id: "u9",
    name: "Beam Monitor Lightbar",
    category: "Utilities",
    price: 110.00,
    rating: 4.7,
    reviewsCount: 67,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Space-saving task light that clamps onto your monitor screen. Eliminates glare and screen reflection to reduce eye strain during late night work.",
    features: ["Asymmetric optical design", "No screen glare reflection", "Wireless desktop dial", "Adjustable color temperature"],
    colors: ["#111827"]
  },
  {
    id: "u10",
    name: "Nest Desk Organizer",
    category: "Utilities",
    price: 75.00,
    rating: 4.6,
    reviewsCount: 59,
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A solid oak catch-all desk tray featuring a felt-lined base to hold pens, keys, glasses, and daily accessories neatly in one dedicated space.",
    features: ["Solid American Oak", "Merino wool felt lining", "CNC-routed pencil wells", "Rubber protective feet"],
    colors: ["#78350F", "#F59E0B"]
  },
  {
    id: "u11",
    name: "Nomad Tech Case",
    category: "Utilities",
    price: 49.00,
    rating: 4.8,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Organize your tech accessories on the go. Built from water-resistant ballistic nylon with mesh pockets and elastic loops to keep cords safe.",
    features: ["Ballistic nylon shell", "Elastic cable loop grid", "YKK weather-proof zippers", "Soft scratch-free lining"],
    colors: ["#1F2937", "#1E3A8A"]
  },
  {
    id: "u12",
    name: "Horizon Desk Mat",
    category: "Utilities",
    price: 35.00,
    rating: 4.5,
    reviewsCount: 91,
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Premium dual-sided vegan leather desk pad. Highly durable, water-resistant, and easy to clean, adding a professional look to your desktop.",
    features: ["Dual-sided vegan leather", "Water-resistant shield", "Stitched edge border", "Roll-up travel strap"],
    colors: ["#374151", "#1E3A8A"],
    isNew: true
  },
  {
    id: "u13",
    name: "Sleek Desk Pencil Organizer",
    category: "Utilities",
    price: 34.99,
    rating: 4.6,
    reviewsCount: 42,
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Anodized aluminum desk pencil holder with a weighted base. Sleek chamfered edges and partition walls to organize your premium writing tools.",
    features: ["Anodized aluminum construct", "Weighted silicone base", "Internal partitions", "Micro-suede bottom"],
    colors: ["#4B5563", "#D1D5DB"]
  },
  {
    id: "u14",
    name: "Mag-Grip Desk Cable Holder",
    category: "Utilities",
    price: 24.50,
    rating: 4.8,
    reviewsCount: 95,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Keep your cords from sliding off the desk. Premium matte silicone weight with magnetic collar pieces that snap your charging cables securely in place.",
    features: ["Heavy non-slip silicone body", "3 magnetic collar attachments", "Compatible with all cable sizes", "Minimal footprint"],
    colors: ["#1F2937", "#4B5563"]
  },
  {
    id: "u15",
    name: "Hydro-Mister Humidifier",
    category: "Utilities",
    price: 59.00,
    rating: 4.5,
    reviewsCount: 74,
    image: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Ultrasonic cool mist humidifier with a water tank and soft warm ambient glow. Runs silently for up to 8 hours to maintain perfect humidity at your desk.",
    features: ["Ultrasonic whisper quiet", "Warm ambient light feature", "Auto shut-off protection", "USB-C power connection"],
    colors: ["#ffffff", "#1F2937"],
    isNew: true
  },
  {
    id: "u16",
    name: "Minimalist Card Wallet",
    category: "Utilities",
    price: 45.00,
    rating: 4.7,
    reviewsCount: 156,
    image: "https://images.unsplash.com/photo-1627124718515-47fe26816041?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Slim RFID-blocking card sleeve handcrafted from premium Crazy Horse leather. Holds up to 6 cards and cash without adding bulk to your pocket.",
    features: ["Crazy Horse pull-up leather", "RFID-blocking inner shield", "Quick-access thumb cutout", "Holds 6 cards and folded cash"],
    colors: ["#78350F", "#000000"]
  },
  {
    id: "u17",
    name: "Tactile Brass Pen",
    category: "Utilities",
    price: 69.00,
    rating: 4.9,
    reviewsCount: 104,
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Precision bolt-action pen machined from solid brass. Develops a unique, beautiful patina over time with daily use. Takes standard Schmidt refills.",
    features: ["Machined solid brass structure", "Smooth bolt-action retraction", "Satisfying weight and balance", "Compatible with G2 refills"],
    colors: ["#F59E0B"],
    isPopular: true
  },
  {
    id: "u18",
    name: "Smart-Lock Bike U-Bar",
    category: "Utilities",
    price: 139.99,
    rating: 4.8,
    reviewsCount: 52,
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Keep your bicycle secure with keyless convenience. Biometric fingerprint scanner unlocks the heavy-duty hardened steel shackle in under 0.5 seconds.",
    features: ["Biometric fingerprint reader", "Hardened steel shackle body", "Weatherproof silicone wrap", "Emergency USB-C key jump"],
    colors: ["#111827"],
    isNew: true
  },
  {
    id: "u19",
    name: "Nano-Suction Phone Stand",
    category: "Utilities",
    price: 32.00,
    rating: 4.6,
    reviewsCount: 63,
    image: "https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An aluminum desk stand utilizing microscopic nano-suction pads to grip your phone securely without magnets, adhesives, or mechanical clamps.",
    features: ["Nano-suction grip technology", "Premium matte aluminum build", "Clean surface wash-to-restore", "Universal device compatibility"],
    colors: ["#4B5563", "#D1D5DB"]
  },
  {
    id: "u20",
    name: "Ultra-Grip Phone Case",
    category: "Utilities",
    price: 29.99,
    rating: 4.7,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Minimalist phone case featuring high-grip textured side rails and a bio-degradable eco-shell structure. MagSafe compatible rings embedded.",
    features: ["100% bio-degradable polymer", "High-tactility grip rails", "MagSafe compatibility rings", "6ft certified drop shield"],
    colors: ["#1F2937", "#047857", "#1E3A8A"]
  },
  {
    id: "u21",
    name: "Lumina LED Desk Lamp",
    category: "Utilities",
    price: 95.00,
    rating: 4.8,
    reviewsCount: 47,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Space-saving desk clamp light with an adjustable goose-neck and dual ambient backlighting. Reduces eye fatigue by balancing desktop contrast.",
    features: ["Flexible silicone neck", "Dual-zone ambient backlights", "Stepless touch dimming panel", "Heavy-duty desk clamp base"],
    colors: ["#111827", "#ffffff"]
  },
  {
    id: "u22",
    name: "Sound-Dampening Desk Pad",
    category: "Utilities",
    price: 49.00,
    rating: 4.5,
    reviewsCount: 119,
    image: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Extra large sound-absorbing desk mat made from thick recycled wool felt. Dampens mechanical keyboard sound while providing soft, warm support.",
    features: ["Thick recycled wool felt", "Extra-large mouse zone", "Dampens typing noise", "Finished stitching details"],
    colors: ["#374151", "#9CA3AF"]
  },

  // JEWELLERY (22 products)
  {
    id: "j1",
    name: "Aura Gold Bangle",
    category: "Jewellery",
    price: 145.00,
    rating: 4.8,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "A stunning, stackable bangle crafted in 18k gold vermeil. Features a sleek, minimalist silhouette that adds a touch of understated elegance.",
    features: ["18k Gold Vermeil", "Sleek minimalist band", "Scratch-resistant coating", "Premium magnetic clasp"],
    colors: ["#F59E0B", "#D1D5DB"],
    sizes: ["S", "M", "L"],
    isPopular: true
  },
  {
    id: "j2",
    name: "Celestial Diamond Ring",
    category: "Jewellery",
    price: 499.00,
    rating: 4.9,
    reviewsCount: 64,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "A conflict-free brilliant-cut diamond set in solid 14k white gold. Featuring a celestial starburst engraving that catches light beautifully.",
    features: ["Solid 14k White Gold", "Conflict-free diamond", "Hand-engraved detail", "Includes certification"],
    colors: ["#D1D5DB"],
    sizes: ["5", "6", "7", "8"],
    isNew: true
  },
  {
    id: "j3",
    name: "Lunar Pearl Earrings",
    category: "Jewellery",
    price: 120.00,
    rating: 4.7,
    reviewsCount: 78,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Elegant drop earrings featuring natural baroque freshwater pearls suspended from polished sterling silver french ear wires.",
    features: ["Baroque freshwater pearls", "925 Sterling Silver hooks", "Each pearl unique", "Hypoallergenic wires"],
    colors: ["#D1D5DB"]
  },
  {
    id: "j4",
    name: "Solar Medallion Necklace",
    category: "Jewellery",
    price: 175.00,
    rating: 4.8,
    reviewsCount: 114,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An embossed sun emblem medallion pendant hanging from a sturdy curb chain. Handcrafted in 18k gold vermeil over sterling silver.",
    features: ["18k gold vermeil", "Embossed sun motif", "20-inch curb chain", "Lobster clasp enclosure"],
    colors: ["#F59E0B"],
    isPopular: true
  },
  {
    id: "j5",
    name: "Zenith Silver Cuff",
    category: "Jewellery",
    price: 135.00,
    rating: 4.6,
    reviewsCount: 53,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A wide, hand-hammered open cuff bracelet crafted from high-quality 925 sterling silver, providing a raw textured and striking design.",
    features: ["925 Sterling Silver", "Hand-hammered texture", "Adjustable open cuff fit", "Brushed metal finish"],
    colors: ["#D1D5DB"]
  },
  {
    id: "j6",
    name: "Solitaire Emerald Studs",
    category: "Jewellery",
    price: 250.00,
    rating: 4.8,
    reviewsCount: 42,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Stunning princess-cut green Colombian emeralds set in solid 14k yellow gold four-prong baskets. Features secure threaded screw backings.",
    features: ["Colombian emeralds", "Solid 14k Yellow Gold basket", "Threaded screw posts", "Conflict-free origin"],
    colors: ["#F59E0B"]
  },
  {
    id: "j7",
    name: "Dune Textured Ring",
    category: "Jewellery",
    price: 195.00,
    rating: 4.7,
    reviewsCount: 36,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An organic, sand-cast wedding band style ring crafted from solid 14k yellow gold, featuring a unique shifting dunes ripple texture.",
    features: ["Solid 14k Yellow Gold", "Sand-cast ripple pattern", "Comfort-fit inside wall", "Eco-friendly recycled gold"],
    colors: ["#F59E0B"],
    sizes: ["6", "7", "8", "9"]
  },
  {
    id: "j8",
    name: "Horizon Chain Bracelet",
    category: "Jewellery",
    price: 110.00,
    rating: 4.5,
    reviewsCount: 89,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A modern paperclip link chain bracelet. Perfect for layering or wearing solo. Handcrafted in heavy 18k gold plating over sterling silver.",
    features: ["18k gold plated silver", "Paperclip link styling", "Adjustable length loops", "Safe for sensitive skin"],
    colors: ["#F59E0B"],
    isNew: true
  },
  {
    id: "j9",
    name: "Aurora Opal Pendant",
    category: "Jewellery",
    price: 220.00,
    rating: 4.9,
    reviewsCount: 71,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A fire Ethiopian opal prong-set in 14k rose gold on a delicate link chain. The opal shifts hues with movement, mirroring the northern lights.",
    features: ["Ethiopian fire opal", "Solid 14k Rose Gold clasp", "Delicate chain structure", "High flash reflection"],
    colors: ["#BE185D"]
  },
  {
    id: "j10",
    name: "Stellar Star Huggies",
    category: "Jewellery",
    price: 85.00,
    rating: 4.6,
    reviewsCount: 121,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Delicate hoop earrings featuring diamond-paved starburst drop charms. Made from 925 sterling silver with rhodium anti-tarnish plating.",
    features: ["Diamond cubic zirconia", "925 Sterling Silver hoops", "Star drop charms", "Click-latch secure lock"],
    colors: ["#D1D5DB"],
    isPopular: true
  },
  {
    id: "j11",
    name: "Driftwood Hoop Earrings",
    category: "Jewellery",
    price: 95.00,
    rating: 4.7,
    reviewsCount: 54,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Classic hoops textured with an organic driftwood grain pattern. Handcrafted in solid polished sterling silver with a satin interior polish.",
    features: ["Polished Sterling Silver", "Textured organic wood pattern", "Medium size hoops", "Push post closures"],
    colors: ["#D1D5DB"]
  },
  {
    id: "j12",
    name: "Trinity Band Set",
    category: "Jewellery",
    price: 160.00,
    rating: 4.8,
    reviewsCount: 63,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A set of three stackable bands in yellow gold, rose gold, and silver. Features a subtle braided pattern for a cohesive, classic styling.",
    features: ["Set of 3 stack rings", "Multi-metal gold/silver/rose", "Comfort-fit rounded band", "Braided twist design"],
    colors: ["#F59E0B", "#BE185D", "#D1D5DB"],
    sizes: ["5", "6", "7", "8"],
    isNew: true
  },
  {
    id: "j13",
    name: "Vermeil Arch Pendant",
    category: "Jewellery",
    price: 155.00,
    rating: 4.7,
    reviewsCount: 46,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An elegant, clean-lined arch pendant necklace inspired by architectural arches. Handcrafted in heavy 18k gold plating over sterling silver.",
    features: ["18k gold vermeil finish", "Architectural arch pendant", "18-inch adjustable chain", "Secure spring clasp lock"],
    colors: ["#F59E0B"]
  },
  {
    id: "j14",
    name: "Helix Silver Ear Cuff",
    category: "Jewellery",
    price: 48.00,
    rating: 4.6,
    reviewsCount: 120,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A minimalist helix wrap-around ear cuff requiring no piercing. Gently hugs the outer cartilage for a chic, modern layered look.",
    features: ["925 Sterling Silver construct", "Adjustable pinch-to-fit band", "No piercing required", "Polished mirror surface finish"],
    colors: ["#D1D5DB"],
    isNew: true
  },
  {
    id: "j15",
    name: "Sienna Amber Ring",
    category: "Jewellery",
    price: 110.00,
    rating: 4.8,
    reviewsCount: 31,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A striking ring centering a polished cabochon of genuine Baltic amber. The sterling silver bezel features delicate sand-cast texturing.",
    features: ["Genuine Baltic amber stone", "925 Sterling Silver band", "Raw sand-cast bezel texture", "Handcrafted in Poland"],
    colors: ["#F59E0B", "#D1D5DB"],
    sizes: ["6", "7", "8"]
  },
  {
    id: "j16",
    name: "Cascade Drop Earrings",
    category: "Jewellery",
    price: 215.00,
    rating: 4.9,
    reviewsCount: 57,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Multi-stone cascading drop earrings featuring small aquamarine and clear quartz beads linked by fine gold fill wires.",
    features: ["Natural aquamarine & quartz", "14k Gold fill metal hooks", "Delicate cascade alignment", "Extremely lightweight structure"],
    colors: ["#F59E0B"],
    isPopular: true
  },
  {
    id: "j17",
    name: "Infinity Link Choker",
    category: "Jewellery",
    price: 185.00,
    rating: 4.7,
    reviewsCount: 84,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A chunky, statement-making interlocked infinity link choker. Crafted in gold vermeil, it sits flat along the collarbone.",
    features: ["Thick 18k gold vermeil link", "Flat-lying collarbone design", "Infinity link pattern detail", "Lobster clasp fastening hook"],
    colors: ["#F59E0B"]
  },
  {
    id: "j18",
    name: "Solstice Diamond Studs",
    category: "Jewellery",
    price: 350.00,
    rating: 4.9,
    reviewsCount: 49,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Lab-grown brilliant-cut round diamonds set in a star-cut yellow gold backing, giving the illusion of a glowing starburst.",
    features: ["Lab-grown brilliant diamonds", "Solid 14k Yellow Gold base", "Starburst bezel shape cut", "Comfort friction back posts"],
    colors: ["#F59E0B"],
    isNew: true
  },
  {
    id: "j19",
    name: "Lotus Petal Ring",
    category: "Jewellery",
    price: 95.00,
    rating: 4.6,
    reviewsCount: 73,
    image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Delicate overlapping silver petal ring inspired by the lotus flower. High-polish inner band with a softly satin-finished exterior petal face.",
    features: ["925 Sterling Silver design", "Satin exterior petal finish", "Overlapping band structure", "Slightly adjustable open back"],
    colors: ["#D1D5DB"],
    sizes: ["5", "6", "7", "8"]
  },
  {
    id: "j20",
    name: "Nova Gold Anklet",
    category: "Jewellery",
    price: 75.00,
    rating: 4.5,
    reviewsCount: 68,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A delicate gold-filled anklet carrying five tiny star-cut charms that catch light as you walk. Perfect for sunny beach summer look.",
    features: ["14k Gold fill wire chain", "5 star charm attachments", "9-inch link with 1-inch extender", "Snag-free rounded link edges"],
    colors: ["#F59E0B"]
  },
  {
    id: "j21",
    name: "Elysian Pearl Choker",
    category: "Jewellery",
    price: 180.00,
    rating: 4.8,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A row of hand-selected freshwater pearls strung on a silk cord. Completed with an elegant architectural gold vermeil bar toggle clasp.",
    features: ["Cultured freshwater pearls", "Genuine silk cord knotting", "Vermeil bar toggle clasp", "Perfect 15-inch choker length"],
    colors: ["#ffffff", "#F59E0B"],
    isPopular: true
  },
  {
    id: "j22",
    name: "Lumina Wave Bangle",
    category: "Jewellery",
    price: 145.00,
    rating: 4.7,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Sleek undulating sterling silver bangle mimicking ocean wave crests. Features a spring hinge and a secure push button clasp.",
    features: ["925 Sterling Silver band", "Fluid wave curve contours", "Hidden hinge mechanism", "High-polish mirror surface"],
    colors: ["#D1D5DB"],
    sizes: ["S", "M", "L"],
    isNew: true
  },

  // DRESSES (22 products)
  {
    id: "d1",
    name: "Aura Silk Wrap Dress",
    category: "Dresses",
    price: 189.50,
    rating: 4.7,
    reviewsCount: 118,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1539008835140-73604de08216?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Flowing elegance designed to capture attention. Made from organic mulberry silk, the Aura Wrap Dress features an adjustable waist tie and a soft sheen that adapts beautifully.",
    features: ["100% Organic Mulberry Silk", "Adjustable self-tie wrap", "Breathable silk weave", "Naturally hypoallergenic"],
    colors: ["#BE185D", "#047857", "#4338CA"],
    sizes: ["XS", "S", "M", "L"],
    isPopular: true
  },
  {
    id: "d2",
    name: "Linen Summer Sundress",
    category: "Dresses",
    price: 95.00,
    rating: 4.6,
    reviewsCount: 52,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=400&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80",
    ],
    video: "/assets/videos/demoVideo.mp4",
    description: "Stay cool and stylish all summer. Crafted from 100% organic pre-washed linen, featuring a button-down front, handy side pockets, and comfortable wide shoulder straps.",
    features: ["100% Organic linen", "Functional side pockets", "Real coconut shell buttons", "A-line flow silhouette"],
    colors: ["#ffffff", "#F3F4F6", "#F59E0B"],
    sizes: ["S", "M", "L"],
    isNew: true
  },
  {
    id: "d3",
    name: "Velvet Gala Gown",
    category: "Dresses",
    price: 280.00,
    rating: 4.9,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A formal floor-length gown cut from heavy, plush velvet. Designed with an elegant off-the-shoulder wrap neckline and a dramatic leg slit.",
    features: ["Plush heavy velvet", "Off-shoulder wrap top", "Floor-length split hem", "Concealed back zip"],
    colors: ["#111827", "#7F1D1D", "#1E3A8A"],
    sizes: ["S", "M", "L", "XL"],
    isPopular: true
  },
  {
    id: "d4",
    name: "Dune Cotton Midi",
    category: "Dresses",
    price: 125.00,
    rating: 4.7,
    reviewsCount: 61,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A comfortable tiered midi dress crafted from textured double-gauze organic cotton. Features adjustable spaghetti straps and a smocked back panel.",
    features: ["100% Organic cotton gauze", "Smocked stretch back panel", "Tiered flow skirt", "Adjustable spaghetti straps"],
    colors: ["#F59E0B", "#F3F4F6"]
  },
  {
    id: "d5",
    name: "Solana Knit Dress",
    category: "Dresses",
    price: 110.00,
    rating: 4.6,
    reviewsCount: 44,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A flattering ribbed halter maxi dress knit from soft modal. Features a high neckline, open back styling, and a straight column silhouette.",
    features: ["Ultra-soft ribbed modal", "Halter neck with open back", "Column maxi fit", "Stretchy ribbed weave"],
    colors: ["#000000", "#047857"],
    isNew: true
  },
  {
    id: "d6",
    name: "Celeste Slip Dress",
    category: "Dresses",
    price: 140.00,
    rating: 4.8,
    reviewsCount: 97,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A classic bias-cut satin slip midi dress that hugs curves beautifully. Features a cowled neckline and delicate crossover adjustable back straps.",
    features: ["Heavy weight satin", "Bias-cut for fluid drape", "Cowl drape neck", "Adjustable cross straps"],
    colors: ["#ffffff", "#1E3A8A", "#BE185D"],
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: "d7",
    name: "Meadow Floral Smock",
    category: "Dresses",
    price: 115.00,
    rating: 4.5,
    reviewsCount: 38,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Vintage floral print smock dress featuring a fitted smocked bodice, sweetheart neckline, and voluminous short puff sleeves.",
    features: ["Cotton poplin print", "Fitted smocked bodice", "Sweetheart neck puff sleeves", "Elasticated ruffle cuffs"],
    colors: ["#BE185D", "#F3F4F6"]
  },
  {
    id: "d8",
    name: "Riviera Linen Shirtdress",
    category: "Dresses",
    price: 130.00,
    rating: 4.7,
    reviewsCount: 79,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A relaxed utility-style linen shirtdress. Features a full button-down front placket, optional matching waist tie, and chest patch pockets.",
    features: ["100% Belgian Linen", "Removable waist belt tie", "Utility patch pockets", "Classic button-down collar"],
    colors: ["#78350F", "#ffffff"],
    isPopular: true
  },
  {
    id: "d9",
    name: "Zenith Pleated Maxi",
    category: "Dresses",
    price: 210.00,
    rating: 4.8,
    reviewsCount: 56,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A stunning accordion-pleated georgette maxi dress featuring a high halter neck and a keyhole back opening. Flows beautifully with step movement.",
    features: ["Accordion pleated georgette", "Halter neck keyhole back", "Fully satin lined", "Sweeping floor length"],
    colors: ["#4338CA", "#047857"]
  },
  {
    id: "d10",
    name: "Dahlia Tulle Gown",
    category: "Dresses",
    price: 240.00,
    rating: 4.9,
    reviewsCount: 73,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A magical midi cocktail dress made from layers of soft pleated tulle, featuring a structured built-in corset bodice for an hourglass silhouette.",
    features: ["Layered fine tulle", "Built-in structured corset", "Concealed back zip", "A-line voluminous skirt"],
    colors: ["#ffffff", "#000000"],
    isNew: true
  },
  {
    id: "d11",
    name: "Horizon Ribbed Midi",
    category: "Dresses",
    price: 85.00,
    rating: 4.6,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A casual, sporty bodycon midi dress knit in thick ribbed cotton. Designed with a scoop neckline and racerback details for daily wear comfort.",
    features: ["Thick ribbed cotton blend", "Racerback scoop neck", "Side walk vent slit", "High stretch retention"],
    colors: ["#1F2937", "#BE185D"]
  },
  {
    id: "d12",
    name: "Oasis Poplin Dress",
    category: "Dresses",
    price: 120.00,
    rating: 4.7,
    reviewsCount: 65,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An easy everyday dress cut from crisp organic cotton poplin. Features a tiered midi skirt, elasticated square neckline, and side seam pockets.",
    features: ["100% Organic cotton poplin", "Elasticated square neck", "Side seam pockets", "Shirred bodice detail"],
    colors: ["#047857", "#ffffff"],
    isNew: true
  },
  {
    id: "d13",
    name: "Luna Satin Midi Dress",
    category: "Dresses",
    price: 165.00,
    rating: 4.8,
    reviewsCount: 74,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Understated elegance. Fluid bias-cut midi slip dress featuring a deep cowl front neckline and cross-back spaghetti straps.",
    features: ["Ultra-soft fluid satin", "Elegant cowl drape front", "Low scoop cross strap back", "Lined front bust bodice"],
    colors: ["#1E3A8A", "#111827", "#BE185D"],
    sizes: ["S", "M", "L"],
    isNew: true
  },
  {
    id: "d14",
    name: "Flora Puff Sleeve Dress",
    category: "Dresses",
    price: 135.00,
    rating: 4.6,
    reviewsCount: 82,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Romantic cottagecore midi dress in an all-over delicate wild-flower print. Structured corset-laced bodice with puffy short sleeves.",
    features: ["Breathable cotton print", "Laced structured bustier bodice", "Elasticated puff sleeves", "Tiered ruffle hemline detail"],
    colors: ["#ffffff", "#BE185D"],
    sizes: ["XS", "S", "M", "L"]
  },
  {
    id: "d15",
    name: "Serene Linen Midi",
    category: "Dresses",
    price: 110.00,
    rating: 4.7,
    reviewsCount: 94,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "An easy-going summer dress in organic, breathable linen. Features adjustable tie shoulder straps and a comfortable smocked back.",
    features: ["100% Organic washed linen", "Self-tie bow shoulder straps", "Smocked back stretch panel", "Invisible side zipper"],
    colors: ["#ffffff", "#78350F", "#047857"],
    sizes: ["S", "M", "L"],
    isPopular: true
  },
  {
    id: "d16",
    name: "Elysian Velvet Cocktail",
    category: "Dresses",
    price: 195.00,
    rating: 4.9,
    reviewsCount: 63,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Deep emerald green velvet cocktail dress designed to fit and flare. Featuring an elegant sweetheart neckline and structured internal cups.",
    features: ["Plush stretch cotton velvet", "Sweetheart bustier cup frame", "Fully lined satin lining", "Flares out at midi length"],
    colors: ["#047857", "#111827"],
    sizes: ["S", "M", "L"],
    isNew: true
  },
  {
    id: "d17",
    name: "Oasis Knit Sundress",
    category: "Dresses",
    price: 120.00,
    rating: 4.5,
    reviewsCount: 51,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A breathable, semi-sheer crochet knit maxi dress with a solid slip liner. Sleek round neck and a low, open scoop-back design.",
    features: ["Delicate cotton crochet knit", "Removable mini slip lining", "Low open scoop-back detail", "Drapes to ankle length"],
    colors: ["#ffffff", "#F59E0B"],
    sizes: ["S", "M", "L"]
  },
  {
    id: "d18",
    name: "Stella Sequined Gown",
    category: "Dresses",
    price: 295.00,
    rating: 4.9,
    reviewsCount: 42,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Dazzling floor-length evening gown fully embellished with miniature hand-sewn sequins that catch light with every turn.",
    features: ["Hand-sewn micro sequins", "High-stretch mesh lining", "Floor length pool hem", "Concealed back zipper lock"],
    colors: ["#ffffff", "#000000"],
    sizes: ["S", "M", "L", "XL"],
    isPopular: true
  },
  {
    id: "d19",
    name: "Dahlia Georgette Wrap",
    category: "Dresses",
    price: 145.00,
    rating: 4.7,
    reviewsCount: 68,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A romantic floral georgette wrap midi dress featuring delicate flutter sleeves and a ruffled high-low wrap hemline.",
    features: ["Lightweight georgette print", "Adjustable self-tie belt strap", "Double-layered ruffle skirts", "Flowing flutter cap sleeves"],
    colors: ["#BE185D", "#ffffff"]
  },
  {
    id: "d20",
    name: "Sienna Linen Shirtdress",
    category: "Dresses",
    price: 125.00,
    rating: 4.6,
    reviewsCount: 59,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "Minimalist utility shirtdress in midweight terracotta linen. Designed with a clean hidden button placket and roll-cuff long sleeves.",
    features: ["100% Belgian washed linen", "Hidden button placket front", "Adjustable roll-cuff sleeves", "Removable fabric tie belt"],
    colors: ["#78350F", "#ffffff"],
    sizes: ["S", "M", "L"],
    isNew: true
  },
  {
    id: "d21",
    name: "Amara Tiered Maxi",
    category: "Dresses",
    price: 130.00,
    rating: 4.7,
    reviewsCount: 87,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A breezy tiered cotton maxi dress in a soft washed olive hue. Features a gathered halter tie neck and a sweeping voluminous skirt.",
    features: ["100% Organic crinkle cotton", "Gathered halter neck front", "Adjustable back neck tie bow", "Voluminous tiered sections"],
    colors: ["#047857", "#ffffff"],
    sizes: ["S", "M", "L"]
  },
  {
    id: "d22",
    name: "Vesper Satin Slip",
    category: "Dresses",
    price: 150.00,
    rating: 4.8,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    images: [],
    video: "/assets/videos/demoVideo.mp4",
    description: "A heavy-weight satin slip dress in a warm rose gold shade. Bias-cut to drape the body beautifully with clean french seams.",
    features: ["Heavy-weight satin construct", "Bias-cut silhouette drape", "Elegant square neckline", "Adjustable slider straps"],
    colors: ["#F59E0B", "#BE185D"],
    sizes: ["XS", "S", "M", "L"],
    isPopular: true
  }
];
